# coding: utf-8

"""
    Messente Combined API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: messente@messente.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import messente_api
from messente_api.models.fetch_blacklist_success import FetchBlacklistSuccess  # noqa: E501
from messente_api.rest import ApiException


class TestFetchBlacklistSuccess(unittest.TestCase):
    """FetchBlacklistSuccess unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFetchBlacklistSuccess(self):
        """Test FetchBlacklistSuccess"""
        # FIXME: construct object with mandatory attributes with example values
        # model = messente_api.models.fetch_blacklist_success.FetchBlacklistSuccess()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
