# coding: utf-8

"""
    Messente API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: messente@messente.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import messente_api
from messente_api.api.blacklist_api import BlacklistApi  # noqa: E501
from messente_api.rest import ApiException


class TestBlacklistApi(unittest.TestCase):
    """BlacklistApi unit test stubs"""

    def setUp(self):
        self.api = messente_api.api.blacklist_api.BlacklistApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_to_blacklist(self):
        """Test case for add_to_blacklist

        Adds a phone number to the blacklist.  # noqa: E501
        """
        pass

    def test_delete_from_blacklist(self):
        """Test case for delete_from_blacklist

        Deletes a phone number from the blacklist.  # noqa: E501
        """
        pass

    def test_fetch_blacklist(self):
        """Test case for fetch_blacklist

        Returns all blacklisted phone numbers.  # noqa: E501
        """
        pass

    def test_is_blacklisted(self):
        """Test case for is_blacklisted

        Checks if a phone number is blacklisted.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
