# coding: utf-8

"""
    Messente API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: messente@messente.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import messente_api
from messente_api.api.groups_api import GroupsApi  # noqa: E501
from messente_api.rest import ApiException


class TestGroupsApi(unittest.TestCase):
    """GroupsApi unit test stubs"""

    def setUp(self):
        self.api = messente_api.api.groups_api.GroupsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_group(self):
        """Test case for create_group

        Creates a new group with the provided name.  # noqa: E501
        """
        pass

    def test_delete_group(self):
        """Test case for delete_group

        Deletes a group.  # noqa: E501
        """
        pass

    def test_fetch_group(self):
        """Test case for fetch_group

        Lists a group.  # noqa: E501
        """
        pass

    def test_fetch_groups(self):
        """Test case for fetch_groups

        Returns all groups.  # noqa: E501
        """
        pass

    def test_update_group(self):
        """Test case for update_group

        Updates a group with the provided name.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
