# coding: utf-8

"""
    Messente Combined API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: messente@messente.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import messente_api
from messente_api.models.group_list_envelope import GroupListEnvelope  # noqa: E501
from messente_api.rest import ApiException


class TestGroupListEnvelope(unittest.TestCase):
    """GroupListEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGroupListEnvelope(self):
        """Test GroupListEnvelope"""
        # FIXME: construct object with mandatory attributes with example values
        # model = messente_api.models.group_list_envelope.GroupListEnvelope()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
