# coding: utf-8

"""
    Messente API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: messente@messente.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import messente_api
from messente_api.api.omnimessage_api import OmnimessageApi  # noqa: E501
from messente_api.rest import ApiException


class TestOmnimessageApi(unittest.TestCase):
    """OmnimessageApi unit test stubs"""

    def setUp(self):
        self.api = messente_api.api.omnimessage_api.OmnimessageApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_cancel_scheduled_message(self):
        """Test case for cancel_scheduled_message

        Cancels a scheduled Omnimessage.  # noqa: E501
        """
        pass

    def test_send_omnimessage(self):
        """Test case for send_omnimessage

        Sends an Omnimessage.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
