# coding: utf-8

"""
    Messente API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: messente@messente.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import messente_api
from messente_api.models.omni_message_create_success_response import OmniMessageCreateSuccessResponse  # noqa: E501
from messente_api.rest import ApiException


class TestOmniMessageCreateSuccessResponse(unittest.TestCase):
    """OmniMessageCreateSuccessResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOmniMessageCreateSuccessResponse(self):
        """Test OmniMessageCreateSuccessResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = messente_api.models.omni_message_create_success_response.OmniMessageCreateSuccessResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
