# coding: utf-8

"""
    Messente API

    [Messente](https://messente.com) is a global provider of messaging and user verification services.  * Send and receive SMS, Viber and WhatsApp messages. * Manage contacts and groups. * Fetch detailed info about phone numbers. * Blacklist phone numbers to make sure you're not sending any unwanted messages.  Messente builds [tools](https://messente.com/documentation) to help organizations connect their services to people anywhere in the world.

    The version of the OpenAPI document: 2.0.0
    Contact: messente@messente.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from messente_api.models.rcs_content_info import RcsContentInfo
from messente_api.models.rcs_rich_card import RcsRichCard
from messente_api.models.rcs_suggestion import RcsSuggestion
from typing import Optional, Set
from typing_extensions import Self

class Rcs(BaseModel):
    """
    RCS message object. Exactly one of 'text', 'content_info' or 'rich_card' must be provided.
    """ # noqa: E501
    channel: Optional[StrictStr] = Field(default='rcs', description="The channel used to deliver the message")
    sender: StrictStr = Field(description="Phone number or alphanumeric sender name")
    validity: Optional[StrictInt] = Field(default=None, description="After how many minutes this channel is considered as failed and the next channel is attempted.Only one of \"ttl\" and \"validity\" can be used.")
    ttl: Optional[StrictInt] = Field(default=None, description="After how many seconds this channel is considered as failed and the next channel is attempted. Only one of \"ttl\" and \"validity\" can be used.")
    text: Optional[Annotated[str, Field(strict=True, max_length=3072)]] = Field(default=None, description="Text content of the RCS message")
    suggestions: Optional[Annotated[List[RcsSuggestion], Field(max_length=11)]] = Field(default=None, description="List of suggestions to include with the message")
    rich_card: Optional[RcsRichCard] = None
    content_info: Optional[RcsContentInfo] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["channel", "sender", "validity", "ttl", "text", "suggestions", "rich_card", "content_info"]

    @field_validator('channel')
    def channel_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['rcs']):
            raise ValueError("must be one of enum values ('rcs')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Rcs from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in suggestions (list)
        _items = []
        if self.suggestions:
            for _item_suggestions in self.suggestions:
                if _item_suggestions:
                    _items.append(_item_suggestions.to_dict())
            _dict['suggestions'] = _items
        # override the default output from pydantic by calling `to_dict()` of rich_card
        if self.rich_card:
            _dict['rich_card'] = self.rich_card.to_dict()
        # override the default output from pydantic by calling `to_dict()` of content_info
        if self.content_info:
            _dict['content_info'] = self.content_info.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Rcs from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "channel": obj.get("channel") if obj.get("channel") is not None else 'rcs',
            "sender": obj.get("sender"),
            "validity": obj.get("validity"),
            "ttl": obj.get("ttl"),
            "text": obj.get("text"),
            "suggestions": [RcsSuggestion.from_dict(_item) for _item in obj["suggestions"]] if obj.get("suggestions") is not None else None,
            "rich_card": RcsRichCard.from_dict(obj["rich_card"]) if obj.get("rich_card") is not None else None,
            "content_info": RcsContentInfo.from_dict(obj["content_info"]) if obj.get("content_info") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


