# coding: utf-8

"""
    Messente API

    [Messente](https://messente.com) is a global provider of messaging and user verification services.  * Send and receive SMS, Viber and WhatsApp messages. * Manage contacts and groups. * Fetch detailed info about phone numbers. * Blacklist phone numbers to make sure you're not sending any unwanted messages.  Messente builds [tools](https://messente.com/documentation) to help organizations connect their services to people anywhere in the world.

    The version of the OpenAPI document: 2.1.0
    Contact: messente@messente.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from messente_api.models.rcs_create_calendar_event_action import RcsCreateCalendarEventAction
from messente_api.models.rcs_dial_action import RcsDialAction
from messente_api.models.rcs_open_url_action import RcsOpenUrlAction
from messente_api.models.rcs_view_location_action import RcsViewLocationAction
from typing import Optional, Set
from typing_extensions import Self

class RcsSuggestedAction(BaseModel):
    """
    RCS suggested action.
    """ # noqa: E501
    text: Annotated[str, Field(strict=True, max_length=25)] = Field(description="The text of the suggested action. Exactly one of the action fields (types) must be provided.")
    postback_data: Annotated[str, Field(strict=True, max_length=2048)] = Field(description="The postback data associated with the suggested action. This is sent back to the sender when the user selects the suggested action.")
    fallback_url: Optional[Annotated[str, Field(strict=True, max_length=2048)]] = Field(default=None, description="The fallback URL to open if the suggested action is not supported.")
    dial_action: Optional[RcsDialAction] = None
    view_location_action: Optional[RcsViewLocationAction] = None
    create_calendar_event_action: Optional[RcsCreateCalendarEventAction] = None
    open_url_action: Optional[RcsOpenUrlAction] = None
    share_location_action: Optional[Dict[str, Any]] = Field(default=None, description="This action does not have any properties. It simply triggers the share location action.")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["text", "postback_data", "fallback_url", "dial_action", "view_location_action", "create_calendar_event_action", "open_url_action", "share_location_action"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RcsSuggestedAction from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of dial_action
        if self.dial_action:
            _dict['dial_action'] = self.dial_action.to_dict()
        # override the default output from pydantic by calling `to_dict()` of view_location_action
        if self.view_location_action:
            _dict['view_location_action'] = self.view_location_action.to_dict()
        # override the default output from pydantic by calling `to_dict()` of create_calendar_event_action
        if self.create_calendar_event_action:
            _dict['create_calendar_event_action'] = self.create_calendar_event_action.to_dict()
        # override the default output from pydantic by calling `to_dict()` of open_url_action
        if self.open_url_action:
            _dict['open_url_action'] = self.open_url_action.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if fallback_url (nullable) is None
        # and model_fields_set contains the field
        if self.fallback_url is None and "fallback_url" in self.model_fields_set:
            _dict['fallback_url'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RcsSuggestedAction from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "text": obj.get("text"),
            "postback_data": obj.get("postback_data"),
            "fallback_url": obj.get("fallback_url"),
            "dial_action": RcsDialAction.from_dict(obj["dial_action"]) if obj.get("dial_action") is not None else None,
            "view_location_action": RcsViewLocationAction.from_dict(obj["view_location_action"]) if obj.get("view_location_action") is not None else None,
            "create_calendar_event_action": RcsCreateCalendarEventAction.from_dict(obj["create_calendar_event_action"]) if obj.get("create_calendar_event_action") is not None else None,
            "open_url_action": RcsOpenUrlAction.from_dict(obj["open_url_action"]) if obj.get("open_url_action") is not None else None,
            "share_location_action": obj.get("share_location_action")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


