# flake8: noqa

"""
    Messente API

    [Messente](https://messente.com) is a global provider of messaging and user verification services.  * Send and receive SMS, Viber, WhatsApp and Telegram messages. * Manage contacts and groups. * Fetch detailed info about phone numbers. * Blacklist phone numbers to make sure you're not sending any unwanted messages.  Messente builds [tools](https://messente.com/documentation) to help organizations connect their services to people anywhere in the world.  # noqa: E501

    The version of the OpenAPI document: 1.4.0
    Contact: messente@messente.com
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.4.0"

# import ApiClient
from messente_api.api_client import ApiClient

# import Configuration
from messente_api.configuration import Configuration

# import exceptions
from messente_api.exceptions import OpenApiException
from messente_api.exceptions import ApiAttributeError
from messente_api.exceptions import ApiTypeError
from messente_api.exceptions import ApiValueError
from messente_api.exceptions import ApiKeyError
from messente_api.exceptions import ApiException
